### PR TITLE
Converted Node.js dist version facts into puppet functions

### PR DESCRIPTION
**Pull request by sedan07**
**Reasons for this change:**
* Information about the latest/stable version of Node.js has nothing to do with an individual puppet node so it doesn't make sense for it to be a fact.
* Because of the above point it is inefficient to compute the latest and stable versions on every single puppet node instead of just on the Puppet Master (caching does help here though)
* Computing the latest/stable versions as facts doesn't work in a locked down data centre without general outbound access, if these are functions then they only get run if you ask them to be. (i.e. you can just always specify version numbers to prevent them ever been called)

**Other Changes:**
* Name of gemfile from ".gemfile" to the standard "Gemfile" to remove the requirement to specify the location of the gemfile
* Fixed the version of rspec used to < 3.2 to work with ruby 1.8.7 when running tests

### CODE REVIEW

**Comment by willdurand** [comment]
I'm fine with the overall idea, but would you mind revert the change related to the `.gemfile`? (this can be discussed in another issue though)

**Comment by sedan07** [comment]
`.gemfile` change reverted (+ related commits)

**Comment by tomtheun** [comment]
@willdurand, are there any plans to merge this PR and create a new release of this module? Thanks

**Comment by Ma27** [comment]
:+1: seems legit, but you have to rebase your branch because of some merge conflicts. Furthermore this will can be merged in a 2.x release as the removal of facts may cause BC breaks in some environments.

**Comment by Ma27** [comment]
@sedan07 I'll finish this PR for you (cs fixes, resolve conflicts, etc.)
As your PR is the first thing in the queue for 2.0, I'll finish this before starting further tasks.

As this branch contains conflicts, I've decided to merge your changes onto another branch and close this here :)

**Comment by Ma27** [comment]
see #147 for further information

**Pull request closed without merging**
